#!/bin/bash
#
# Build Docker images locally using the Dockerfiles and scripts under ${ROOT}/docker. You should
# only need this if you're modifying things locally that end up within the containers themselves;
# notably, site content (src/docs/ and src/site_source/) does not.

ROOT=$(cd $(dirname $0)/.. && pwd)

# Validate the arguments.
if [ "$#" -lt 1 ]; then
  echo "Usage: script/dockbuild <dirname>..."
  echo
  echo " <dirname>: a Docker container managed by this repository."
  echo -n " available containers:"
  for DIRNAME in $(find ${ROOT}/docker/ -type d -mindepth 1 -maxdepth 1); do
    SHORTNAME=$(basename ${DIRNAME})
    echo -n " ${SHORTNAME}"
  done
  echo
  exit 1
fi

source ${ROOT}/script/common/yaks.sh

for CONTAINER in "$@"; do
  DOCKDIR="${ROOT}/docker/${CONTAINER}"
  DOCKERFILE="${DOCKDIR}/Dockerfile"
  CONTEXTFILE="${DOCKDIR}/buildcontext"

  if [ ! -d "${DOCKDIR}" ] || [ ! -f "${DOCKERFILE}" ] || [ ! -f "${CONTEXTFILE}" ] ; then
    echo "Unrecognized container: ${CONTAINER}"
    continue
  fi

  printf -v RELCONTEXT '%s' $(cat ${CONTEXTFILE})
  CONTEXT=${ROOT}/${RELCONTEXT}

  cp ${DOCKDIR}/Dockerfile ${CONTEXT}/Dockerfile
  docker build --tag devsite/${CONTAINER} ${CONTEXT}
  rm ${CONTEXT}/Dockerfile
done
