#!/bin/bash

if which boot2docker 2>/dev/null 1>&2; then
  boot2docker up 2>/dev/null 1>&2
  $(boot2docker shellinit) 2>/dev/null 1>&2
fi

ROOT=$(cd $(dirname $0)/.. && pwd)

${ROOT}/docker/build/use.sh

docker build --tag devsite/build ${ROOT}
exec docker run \
  --interactive=true --tty=true \
  --volume=${ROOT}/src/docs:/usr/src/docs:ro \
  --volume=${ROOT}/src/site_source:/usr/src/site_source:ro \
  --volume=${ROOT}/Gemfile:/usr/src/Gemfile:ro \
  --volume=${ROOT}/Gemfile.lock:/usr/src/Gemfile.lock:ro \
  devsite/build \
  /usr/src/scripts/preview.sh
